name: zeze_mobile
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  bloc: ^8.1.1
  get_it: ^7.2.0
  shared_preferences: ^2.0.18
  shimmer: ^3.0.0
  cached_network_image: ^3.2.3
  flutter_screenutil: ^5.7.0
  flutter_svg: ^2.0.3

  firebase_core: 
  firebase_auth: 
  google_sign_in: 
  flutter_spinkit: ^5.1.0
  add_2_calendar: ^2.1.2
  flutter_contacts: ^1.1.6
  flutter_phone_direct_caller: ^2.1.1
  url_launcher: ^6.1.10
  contacts_service: ^0.6.3
  permission_handler: ^10.2.0

  porcupine_flutter: ^2.1.6
  speech_to_text: ^6.1.1
  get: ^4.6.5
  flutter_tts: ^3.6.2
  dio:
  geolocator: ^9.0.2
  firebase_storage: 
  image_picker: ^1.0.0
  cloud_firestore: 
  firebase_app_check: ^0.1.4+3
  file_picker: 
  firebase_database:
  intl: ^0.18.1
  font_awesome_flutter: ^10.4.0
  awesome_notifications: ^0.6.19
  location_picker_flutter_map: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true
  assets:
    - assets/images/
